name: Check all Standard Names are following character rules

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  python_functests:
    name: Python Functional Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3

      - name: Run script that checks standard names against character rules
        run: |
          python3 tools/check_name_rules.py
